### ISSUE TITLE
figure out the correct dimension for minimap video

### ISSUE THREAD

**Issue by wwkb123** [xynlophyl/soccertracking#12]

**Comment by xynlophyl** [comment]
update: instead of using matplotlib plot to generate the pitch image for every frame, we extracted the plot into a png file (in assets/) and use that instead for transformations.

issue: but now, when combining minimap image and the original video into one for visualizations, the minimap pitch is displayed with black bars at the edges, which is not ideal. therefore, need to find a solution to remove them (e.g. manually remove the space around the pitch, and retag all pitch keypoints)

**Comment by friendlymatthew** [comment]
Hi, are there any updates to this?
